CREATE TABLE IF NOT EXISTS CREDIT_CARD (
  ID            VARCHAR(255) PRIMARY KEY,
  INITIAL_LIMIT DECIMAL(18,2) NOT NULL,
  USED_LIMIT    DECIMAL(18,2) NOT NULL
);

CREATE TABLE IF NOT EXISTS WITHDRAWAL (
  ID     VARCHAR(255) PRIMARY KEY,
  CARD_ID   VARCHAR(255)    NOT NULL,
  AMOUNT DECIMAL(18,2) NOT NULL,
  foreign key (CARD_ID) references CREDIT_CARD(ID)
);