{
 "title": "Backend App",
 "description": "Backend Application Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "request/sec",
   "type": "stat",
   "description": "Current TPS",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{method=\"GET\",uri=\"root\"}[5m]))"
    }
   ]
  },
  {
   "title": "Request/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{method=\"GET\",uri=\"root\"}[5m])"
    }
   ]
  },
  {
   "title": "Max Response Time",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(quantile_over_time(0.95, com_example_quarkus_BackendResource_timeBackend_seconds_max[5m]))"
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "graph",
   "description": "Average max response time",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " avg(com_example_quarkus_BackendResource_timeBackend_seconds_max)"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "system_cpu_usage" }
   ]
  },
  {
   "title": "Heap Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "MB" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (jvm_memory_used_bytes)/1048576"
    }
   ]
  }
 ]
}